[workspace]
members = [".", "yew-tiptap-build-deps"]

[package]
name = "yew-tiptap"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.5"
urlencoding = "2"
yew = "0.20"
